from database_manager.database_manager import DatabaseManager


class Agent:
    def __init__(self, name, description, topics, output_format):
        """
        Initialize an agent with specified attributes.

        Args:
            name (str): Name of the agent.
            description (str): Description of the agent.
            topics (list): List of topics the agent handles.
            output_format (str): Desired output format for the agent (e.g., "pdf", "link", "image").
        """
        self.name = name
        self.description = description
        self.topics = topics if isinstance(topics, list) else [topics]  # Ensure topics is a list
        self.output_format = output_format
        self.db_manager = DatabaseManager()
        self.initialize_bot()

    def initialize_bot(self):
        """
        Initialize the bot, and insert bot data into database.
        """
        self.db_manager.insert_data(self.name, self.description, self.topics, self.output_format)

    def process_input(self, user_input):
        """
        Process user input and generate a response.

        This method should be implemented by subclasses.

        Args:
            user_input (str): Input provided by the user.

        Returns:
            str: Response generated by the bot.
        """
        raise NotImplementedError("process_input method must be implemented by subclass")