services:
  classifier:
    build: ./classifier_agent

  websocket-server:
    build: ./websocket_server
    environment:
      FLASK_DEBUG: 1
      FLASK_ENV: development
      FLASK_APP: server.py
    ports:
      - "5001:5001"