---
apiVersion: v1
kind: Service
metadata:
  name: python
spec:
  type: LoadBalancer
  selector:
    app: python
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
  labels:
    app: python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
        - name: python
          image: europe-west4-docker.pkg.dev/dverse-423510/websocket-server/python:latest
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: secrets
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: python-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: python
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-dev-ingress
  annotations:
    cert-manager.io/cluster-issuer: "dev-letsencrypt-issuer"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - dev.mysimpleweb.com
      secretName: dev-web-tls-secret
  rules:
    - host: dev.mysimpleweb.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-dev-service
                port:
                  number: 80