apiVersion: v1
kind: Service
metadata:
  name: python
spec:
  selector:
    app: python
  ports:
    - port: 80
      targetPort: 5001  # This should match the container's exposed port
  type: LoadBalancer