class Bot:
    def __init__(self, botId, name, topics, output_format):
        """
        Initialize a bot with specified attributes.

        Args:
            botId (str): Unique identifier for the bot.
            name (str): Name of the bot.
            topics (list): List of topics the bot handles.
            output_format (str): Desired output format for the bot (e.g., "pdf", "link", "image").
        """
        self.botId = botId
        self.name = name
        self.topics = topics if isinstance(topics, list) else [topics]  # Ensure topics is a list
        self.output_format = output_format

    def process_input(self, user_input):
        """
        Process user input and generate a response.

        This method should be implemented by subclasses.

        Args:
            user_input (str): Input provided by the user.

        Returns:
            str: Response generated by the bot.
        """
        raise NotImplementedError("process_input method must be implemented by subclass")