version: '3.8'

services:
  festival-information-agent:
    build: ./FestivalInformationAgent
    ports:
      - '5000:5000'
    environment:
      - OPENAI_API_KEY=OPENAI_API_KEY
      - MONGO_URI=MONGO_URI
   
  youtube-search-agent:
    build: ./YouTubeSearchAgent
    ports:
      - '5001:5001'
      
  google-search-agent:
    build: ./GoogleSearchAgent
    ports:
      - '5002:5002'